### ISSUE TITLE
Menu Page

### ISSUE THREAD

**Issue by thanapdev** [thanapdev/TiguS---FrontEnd-Final-Project#1]

**Comment by LodHoiZ** [comment]
9ef5f28c0dd51fb923944591ce700ad20f3b7409  : add the second catagory

**Comment by LodHoiZ** [comment]
e0cb76132e6a0048e5ab7035724468d15ba7bbed  : Add the third catagory

**Comment by LodHoiZ** [comment]
e399e6fe18a6719e98e3859a678c004598e373e3  : add footer and bootstrap
