### ISSUE TITLE
summary real time calculation

### ISSUE THREAD

**Issue by thanapdev** [thanapdev/TiguS---FrontEnd-Final-Project#13]

**Comment by LodHoiZ** [comment]
b3ea7622979ccdc08553fd603db1193e2d7da4cc : cart is able to add items

**Comment by LodHoiZ** [comment]
dfc39500ad84ac8309f27373c932056710a73bab : Once items are in the cart, user can increase or decrease the amount

**Comment by LodHoiZ** [comment]
571ae6c602e73f3df42a875f1b768255422c855a : The Id's of all the food in the restaurant has been added to the monogDB database

**Comment by LodHoiZ** [comment]
The cart is able to add items from the id in the code but we are not able to pull it from the data base.
The real time calculation in the cart is because of the code
