### ISSUE TITLE
admin manage status for tracking page

### ISSUE THREAD

**Issue by thanapdev** [thanapdev/TiguS---FrontEnd-Final-Project#15]

**Comment by thanapdev** [comment]
d96bd25bbc5b6cc2bf5da502b71d5e0720a8ad6f : admin dashboard

**Comment by thanapdev** [comment]
ee6d75024be99032b6ffcb47c9ba02a6b1ac8fd4 : admin dashboard link to home

**Comment by thanapdev** [comment]
11ddebfb4fab3684a58c202c5dadf8f1a62d4d31 : side bar

**Comment by thanapdev** [comment]
d533876a6d4f221bf376a5e1ed3e6147a3403e16 : side bar content

**Comment by thanapdev** [comment]
63c77d262946568b895c5f41b50fdfe1c3cccbfc : user and admin cannot go to homepage without login

**Comment by LodHoiZ** [comment]
ffef5bf5a238c56ec4c117e486521cb3142b6e35 : add status bar in delivery page

**Comment by LodHoiZ** [comment]
able to change status bar and the bar will increase or decrease corresponding to the status
