### ISSUE TITLE
mongoose data base

### ISSUE THREAD

**Issue by thanapdev** [thanapdev/TiguS---FrontEnd-Final-Project#18]

**Comment by thanapdev** [comment]
1de4c2ce7f2ddbe1674799947d23ac375e279956 : create schema

**Comment by thanapdev** [comment]
e9657384e50e4b7fab9a947754f5dcc4f90c1607 : create db.js to connect to database

**Comment by LodHoiZ** [comment]
fae5083611a60d0d5540381847acc86a98657502 : add food id and admin id to the mongoose database

**Comment by LodHoiZ** [comment]
c6e7ed55f85215a47e882eebb464479ca8406eff : add orders to mongoose database
