### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by LodHoiZ** [thanapdev/TiguS---FrontEnd-Final-Project#2]

**Comment by thanapdev** [comment]
85629a7bf4296908e1a61781f4ba76b92f752505

**Comment by thanapdev** [comment]
df7540b31cb669709ac599e6cd99610139c47166

**Comment by thanapdev** [comment]
cb7b010fa25c0c53805b1e2c87650acb0d8ff1d5 : cover

**Comment by thanapdev** [comment]
3812edfe61118c734c3c87bb5ef14bede83da342 : bootstrap

**Comment by thanapdev** [comment]
d5cf707398450d47719d87cfc4dec7c03f3809cd : img

**Comment by thanapdev** [comment]
29ebd63887201122ad679505b1b0c284ab6cd12c : content
