### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by thanapdev** [thanapdev/TiguS---FrontEnd-Final-Project#8]

**Comment by LodHoiZ** [comment]
38bf6de1586fa77ab892b704c5d0402f057da0f2 : add navbar and sidebar

**Comment by LodHoiZ** [comment]
e79043daf24cc7cc589d5340babd8f7a352e884a

**Comment by LodHoiZ** [comment]
e410565e4cd40c50dbf6ffca4dc541684a17adb4  : add columns and headers

**Comment by LodHoiZ** [comment]
4494101ce03bebbd32818de4a669ea2a19ac8458  : add rows and columns

**Comment by LodHoiZ** [comment]
855dbb3260f0c569eab80507e31f8d85498cd983 : add footers

**Comment by LodHoiZ** [comment]
4ea90c885ab9f8602da7ee7958f55ff7054b689e : add scripts
